name: "Build NPM"

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'rollup.config.js'
      - 'guest-js/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'rollup.config.js'
      - 'guest-js/**'

jobs:
  build-plugin-npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Node stable
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build guest bindings
        run: |
          npm install
          npm run build
