name: "Build NPM"

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'rollup.config.js'
      - 'guest-js/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'rollup.config.js'
      - 'guest-js/**'

permissions:
  contents: read

jobs:
  build-plugin-npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build guest bindings
        run: |
          npm install
          npm run build
