name: "Publish to crates.io and npmjs.org"

on:
  release:
    types: ["published"]

permissions:
  contents: read
  id-token: write

jobs:
  publish-npmjs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - run: npm install && npm run build
      - run: npm publish --provenance --access public
  publish-cratesio:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          sudo apt-get update
          sudo apt-get install -y curl wget file libxdo-dev build-essential libssl-dev libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev
      - run: cargo publish --token ${CRATES_AUTH_TOKEN}
        env:
          CRATES_AUTH_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
