name: "Publish Plugin"

on:
  release:
    types: [ "published" ]

jobs:
  publish-npmjs:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node stable
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Publish npmjs.org Package
        run: | 
            npm install
            npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-cratesio:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y curl wget file libxdo-dev build-essential libssl-dev libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev
      - name: Publish crates.io Package
        run: cargo publish --token ${CRATES_AUTH_TOKEN} 
        env:
          CRATES_AUTH_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
